# Generated by Django 3.2.5 on 2023-12-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20231209_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='matchs',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
